#include "minecraft.h"

#include <fstream>
#include <nlohmann/json.hpp>

// taken from spire
#define SPIRE_VOXEL_LAYOUT_ALL_SAME 0 // all sides use image 0 (e.g. dirt)
#define SPIRE_VOXEL_LAYOUT_TOP_DIFFERENT_BOTTOM_DIFFERENT 1 // top uses image 0, bottom uses image 1, sides use image 2 (e.g. grass)
#define SPIRE_VOXEL_LAYOUT_COLUMN 2 // top and bottom use image 0, sides use image 1 (e.g. log)

struct SpireType {
    unsigned int SpireId; // Min value 1
    std::string MinecraftId;
    unsigned int Layout;
    std::vector<std::string> Textures;
};

std::string EscapeString(const std::string &s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        if (c == '\\') out += "\\\\";
        else if (c == '"') out += "\\\"";
        else out += c;
    }
    return out;
}

std::string LayoutToEnum(unsigned int layout) {
    switch (layout) {
        case SPIRE_VOXEL_LAYOUT_ALL_SAME: return "SPIRE_VOXEL_LAYOUT_ALL_SAME";
        case SPIRE_VOXEL_LAYOUT_TOP_DIFFERENT_BOTTOM_DIFFERENT: return "SPIRE_VOXEL_LAYOUT_TOP_DIFFERENT_BOTTOM_DIFFERENT";
        case SPIRE_VOXEL_LAYOUT_COLUMN: return "SPIRE_VOXEL_LAYOUT_COLUMN";
        default: assert(false);
    }
}

void GenerateMinecraftTypesHeader(const std::vector<SpireType> &types, const std::filesystem::path &path) {
    std::ofstream file(path.string(), std::ios::trunc);
    if (!file.is_open()) {
        std::cerr << "Failed to open MinecraftTypes.h for writing\n";
        return;
    }

    file << "// This file was generated by Tooling/MinecraftRegionConverter\n\n";
    file << "#pragma once\n\n";
    file << "#include \"VoxelRenderer.h\"\n\n";
    file << "#include \"Types/VoxelTypeRegistry.h\"\n\n";
    file << "inline void RegisterMinecraftVoxelTypes(SpireVoxel::VoxelTypeRegistry &voxelTypeRegistry)\n";
    file << "{\n";
    file << "    voxelTypeRegistry.RegisterTypes(std::vector<SpireVoxel::VoxelTypeInfo>{\n";

    for (size_t i = 0; i < types.size(); ++i) {
        const SpireType &t = types[i];

        file << "        {\n";
        file << "            " << t.SpireId << ", {\n";

        for (size_t texIndex = 0; texIndex < t.Textures.size(); ++texIndex) {
            file << "                std::string(SpireVoxel::GetAssetsDirectory()) + \"/Minecraft/"
                    << EscapeString(t.Textures[texIndex]) << "\"";

            if (texIndex + 1 != t.Textures.size())
                file << ",";

            file << "\n";
        }

        file << "            },\n";
        file << "            " << LayoutToEnum(t.Layout) << "\n";
        file << "        }";

        if (i + 1 != types.size())
            file << ",";

        file << "\n";
    }

    file << "    });\n";
    file << "}\n";
}

bool LoadTypes(const std::filesystem::path &path, const std::filesystem::path &file, bool overwriteOutput, std::unordered_map<std::string, int> &types) {
    using json = nlohmann::json;

    std::vector<SpireType> spireTypes;

    std::filesystem::path assets = path / "assets/minecraft/models/block/";
    std::filesystem::path textures = path / "assets/minecraft/textures/block/";

    if (!std::filesystem::exists(assets)) {
        std::cerr << "Minecraft directory " << assets.string() << " does not exist\n";
        return false;
    }

    auto it = std::filesystem::directory_iterator{assets};
    for (auto file : it) {
        std::ifstream f(file.path());
        json data = json::parse(f);

        if (!data.contains("parent")) continue;
        if (!data.contains("textures")) continue;

        std::string parent = data["parent"];
        // Minecraft is very inconsistent on whether they include the prefix or not
        if (parent.starts_with("minecraft:")) parent = parent.substr(10);

        std::string minecraftId = file.path().stem().string(); // file name without extension

        if (parent == "block/cube_all") {
            // one texture
            spireTypes.push_back({
                static_cast<unsigned int>(types.size() + 1), minecraftId,SPIRE_VOXEL_LAYOUT_ALL_SAME, {
                    data["textures"]["all"]
                }
            });
        } else if (parent == "block/block") {
            // 3 textures
            if (!data["textures"].contains("top") || !data["textures"].contains("bottom") || !data["textures"].contains("side")) continue;
            spireTypes.push_back({
                static_cast<unsigned int>(types.size() + 1), minecraftId,SPIRE_VOXEL_LAYOUT_TOP_DIFFERENT_BOTTOM_DIFFERENT, {
                    data["textures"]["top"],
                    data["textures"]["bottom"],
                    data["textures"]["side"]
                }
            });
        } else if (parent == "block/cube_column") {
            spireTypes.push_back({
                static_cast<unsigned int>(types.size() + 1), minecraftId,SPIRE_VOXEL_LAYOUT_COLUMN, {
                    data["textures"]["end"],
                    data["textures"]["side"]
                }
            });
        } else {
            continue; // not included
        }

        types[minecraftId] = types.size() + 1;
    }

    // liquids are hard coded in minecraft code, let's replace them with wool
    types["water"] = types["blue_wool"];
    types["lava"] = types["red_wool"];

    // lookup textures
    for (SpireType &spireType : spireTypes) {
        for (std::string &texture : spireType.Textures) {
            if (texture.starts_with("minecraft:")) texture = texture.substr(10); // again some start with minecraft: and some dont
            if (!texture.starts_with("block/")) {
                std::cerr << "invalid texture " << texture << "\n";
                continue;
            }
            texture = texture.substr(6); // remove block/
            texture += ".png";
        }
    }

    if (!overwriteOutput && std::filesystem::exists(file)) {
        std::cerr << "File " << file.string() << " already exists\n";
        return false;
    }
    GenerateMinecraftTypesHeader(spireTypes, file);

    return true;
}
