#pragma once

#define IMGUI_DEFINE_MATH_OPERATORS
#include "imgui/imgui.h"
#include "imgui/backends/imgui_impl_glfw.h"
#include "imgui/backends/imgui_impl_vulkan.h"

#include "Core/Engine.h"
#include "Core/Application.h"
#include "Window/Window.h"

#include "Engine/Rendering/RenderingManager.h"
#include "Rendering/Core/RenderingCommandManager.h"
#include "Rendering/Core/VulkanQueue.h"
#include "Rendering/Core/ShaderCompiler.h"
#include "Rendering/Core/Pipelines/GraphicsPipeline.h"
#include "Rendering/Core/Pipelines/ComputePipeline.h"
#include "Engine/Rendering/Memory/BufferManager.h"
#include "Rendering/Descriptors/DescriptorSet.h"
#include "Rendering/Descriptors/DescriptorPool.h"
#include "Rendering/Descriptors/DescriptorManager.h"
#include "Rendering/Descriptors/DescriptorSetLayoutList.h"
#include "Rendering/Descriptors/DescriptorCreator.h"
#include "Rendering/Memory/ImageManager.h"
#include "Engine/Rendering/Core/Swapchain.h"
#include "Rendering/Core/LogicalDevice.h"
#include "Rendering/Core/RenderingSync.h"
#include "Rendering/Renderers/Renderer.h"
#include "Rendering/Memory/VulkanBuffer.h"
#include "Rendering/Memory/VulkanImage.h"
#include "Rendering/Scene/SceneModels.h"
#include "Rendering/Scene/PushConstants.h"
#include "Rendering/Renderers/ImGuiRenderer.h"
#include "Engine/Rendering/Core/RenderingDeviceManager.h"
#include "Rendering/Scene/SceneImages.h"
#include "Rendering/Memory/PerImageBuffer.h"

#include "Engine/Resources/ImageLoader.h"
#include "Engine/Resources/Model.h"
#include "Engine/Resources/Mesh.h"
#include "Engine/Resources/ModelLoader.h"

#include "Engine/Utils/Camera/Camera.h"
#include "Engine/Utils/Timer.h"